# coding: utf-8

"""
    fave

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.0-prealpha
    Contact: sabyasachi@datafund.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fave_add_documents(self):
        """Test case for fave_add_documents

        """
        pass

    def test_fave_create_collection(self):
        """Test case for fave_create_collection

        """
        pass

    def test_fave_delete_collection(self):
        """Test case for fave_delete_collection

        """
        pass

    def test_fave_get_documents(self):
        """Test case for fave_get_documents

        """
        pass

    def test_fave_get_nearest_documents(self):
        """Test case for fave_get_nearest_documents

        """
        pass

    def test_fave_root(self):
        """Test case for fave_root

        """
        pass


if __name__ == '__main__':
    unittest.main()
