# coding: utf-8

"""
    fave

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.0-prealpha
    Contact: sabyasachi@datafund.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.ok_response import OKResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestOKResponse(unittest.TestCase):
    """OKResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOKResponse(self):
        """Test OKResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.ok_response.OKResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
