# coding: utf-8

"""
    fave

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.0-prealpha
    Contact: sabyasachi@datafund.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.error_response_error import ErrorResponseError  # noqa: E501
from swagger_client.rest import ApiException


class TestErrorResponseError(unittest.TestCase):
    """ErrorResponseError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorResponseError(self):
        """Test ErrorResponseError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.error_response_error.ErrorResponseError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
