# coding: utf-8

# flake8: noqa

"""
    fave

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.0-prealpha
    Contact: sabyasachi@datafund.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.default_api import DefaultApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.add_documents_request import AddDocumentsRequest
from swagger_client.models.collection import Collection
from swagger_client.models.document import Document
from swagger_client.models.error_response import ErrorResponse
from swagger_client.models.error_response_error import ErrorResponseError
from swagger_client.models.index import Index
from swagger_client.models.model_property import ModelProperty
from swagger_client.models.nearest_documents_request import NearestDocumentsRequest
from swagger_client.models.nearest_documents_response import NearestDocumentsResponse
from swagger_client.models.ok_response import OKResponse
